### PR TITLE
support Vimeo and youtube short form

### PR DESCRIPTION
**Pull request by santhoshbalusamy**
support Vimeo and youtube short form
eg: https://youtu.be/{ID}

### CODE REVIEW

**Comment by santhoshbalusamy** [comment]
@silencesys It is very urgent. can you please review my PR!!

**Comment by alexanderkogan** [comment]
I'm not really a maintainer of this, I'm sorry.

**Comment by santhoshbalusamy** [comment]
@silencesys Can you please update the npm package and Yarn package?

**Comment by santhoshbalusamy** [comment]
@silencesys I am not able to get the latest changes from npm and yarn.
can you please update this into npm and yarn?

**Comment by silencesys** [comment]
@santhoshbalusamy sorry for the waiting, it is updated.

**Pull request merged**
